### ISSUE TITLE
Enhance the UI of Footer.

### ISSUE THREAD

**Issue by Sudhanshu248** [OWASP/www-project-threat-dragon#112]
I would like to enhance the UI of footer the website by fixing the social links or content properly at correct place.

![Screenshot 2024-12-26 231229](https://github.com/user-attachments/assets/3d1dd471-53da-4ff9-bd0a-a76668ee4ef7)

**Comment by Sudhanshu248** [comment]
@jgadsden Please assign me this issue.

**Comment by jgadsden** [comment]
This is generated by the OWASP foundation and is not part of the www-project-threat-dragon repo itself
@Sudhanshu248 it is worth raising this in the OWASP slack channels
