### ISSUE TITLE
Improve the UI of the Navbar Section 

### ISSUE THREAD

**Issue by Himanshu-kumar025** [OWASP/www-project-threat-dragon#113]
I Like to improve the UI of the Navbar of this project.

![Screenshot 2024-12-26 231531](https://github.com/user-attachments/assets/3ce4e1c3-9d6d-433a-a11e-d81ab61e0b9e)

**Comment by jgadsden** [comment]
This is generated by the OWASP foundation and is not part of the www-project-threat-dragon repo itself
@Sudhanshu248 it is worth raising this in the OWASP slack channels

**Comment by jgadsden** [comment]
This is generated by the OWASP foundation and is not part of the www-project-threat-dragon repo itself
@Sudhanshu248 it is worth raising this in the OWASP slack channels
