### ISSUE TITLE
Change the structure of Corporate Supporters

### ISSUE THREAD

**Issue by Sudhanshu248** [OWASP/www-project-threat-dragon#114]
The UI of Corporate Supporters is not looks good. I would like to modify the UI of it.

![Screenshot 2024-12-26 232231](https://github.com/user-attachments/assets/0c8cff3c-c43b-4a9f-96e9-e747ea4170f2)

**Comment by Sudhanshu248** [comment]
@jgadsden Please assign me this issue.

**Comment by jgadsden** [comment]
This is generated by the OWASP foundation and is not part of the www-project-threat-dragon repo itself
@Sudhanshu248 it is worth raising this in the OWASP slack channels

**Comment by Sudhanshu248** [comment]
@jgadsden Can you assign me some issues on which i can work?
