### ISSUE TITLE
Improve the UI of this sector.

### ISSUE THREAD

**Issue by Himanshu-kumar025** [OWASP/www-project-threat-dragon#115]
I would you like to improve the UI of this sector.

![Screenshot 2024-12-26 232542](https://github.com/user-attachments/assets/2aadce91-01a8-4f46-a3be-6427a697d887)

**Comment by jgadsden** [comment]
This is generated by the OWASP foundation and is not part of the www-project-threat-dragon repo itself
@Himanshu-kumar025  it is worth raising this in the OWASP slack channels
