### ISSUE TITLE
Fix-up title and website added

### ISSUE THREAD

**Issue by jgadsden** [OWASP/www-project-threat-dragon#2]
It would be good for the repo title to be 'OWASP Foundation project Threat Dragon' instead of 'OWASP Foundation Web Respository '. In addition the website field should be 'https://owasp.org/www-project-threat-dragon/'

**Comment by jgadsden** [comment]
Hello @hblankenship - is it OK to change the title of this repo? I do not seem to have the permissions to do it, but at the moment it reads 'OWASP Foundation Web Respository ' but this has a typo in it. It would be great if it could read 'OWASP Foundation project Threat Dragon' or something similar

**Comment by hblankenship** [comment]
I changed it to OWASP Foundation Threat Dragon Project Web Repository (to differentiate from the code repository - unless you plan to merge these too?  That isn't required or expected).

**Comment by jgadsden** [comment]
Many thanks @hblankenship - just the job
