### ISSUE TITLE
Styling Issue: Words sticking to the end of the screen at 90% width

### ISSUE THREAD

**Issue by SharanRP** [OWASP/www-project-threat-dragon#74]
I encountered a styling issue where, at a 90% screen width, the words within a block are sticking to the very end of the screen. This behavior is not observed at other screen widths, where the layout appears as expected.

Steps to Reproduce:
Open the application/page in a browser.
Resize the browser window to 90% width.
Navigate to the specific page or section where the issue is occurring.
Observe that the words within a block stick to the very end of the screen.
Expected Behavior:
"At 90% screen width, there should be an appropriate margin around the block, preventing the words from sticking to the edge of the screen. This behavior is expected to be consistent across different screen widths."

Actual Behavior:
"At 90% or 100% screen width, the words within a block are not respecting the margin, and they appear to be sticking to the very end of the screen. This issue is not present at other screen widths."

Screenshots:
[![At 90%](https://i.imgur.com/laqfhjH.png)](https://i.imgur.com/laqfhjH.png)

[![At 80%](https://i.imgur.com/Zz9qlX5.png)](https://i.imgur.com/Zz9qlX5.png)

I have tested this issue on multiple browsers and devices, and the problem persists. The issue is specific to a particular screen width (90% or 100%).

Conclusion:
This styling issue affects the visual presentation of the content, specifically at a 90% screen width, and needs attention to ensure a consistent and visually pleasing layout across different screen sizes.

**Comment by hblankenship** [comment]
There is likely an @media thing at play here. I will look into it when I get a chance but re-styling the OWASP theme is not fully supported. For completeness, what screen resolution are you running at @SharanRP?

**Comment by SharanRP** [comment]
1366x768

**Comment by hblankenship** [comment]
Rebuild and see if it is any better now?

**Comment by jgadsden** [comment]
Thanks @hblankenship 
Pages have been rebuilt and deployed if you want to test it @SharanRP ?

**Comment by SharanRP** [comment]
Greate , pages have now improved,
also I reported another bug , while viewing the webpage in phone screen,shall I post it here , or open a new issue?

**Comment by jgadsden** [comment]
Hello @SharanRP , if you could create a new issue that would be great
