### ISSUE TITLE
Inconsistent header behaviour in small screens

### ISSUE THREAD

**Issue by Santhoshmani1** [OWASP/www-project-threat-dragon#76]
## Issue : 
The Header has inconsistent styling in smaller devices for screen resolution < 420px and can be improved.

![Screenshot 2024-01-19 074421](https://github.com/OWASP/www-project-threat-dragon/assets/119673958/f05782b0-39b5-4a4c-bda8-eb78534c8d29)

**Solution 1**
The buttons wrapper can be used the css flex property, so that the styles are consistent and responsive.
![Screenshot 2024-01-19 074344](https://github.com/OWASP/www-project-threat-dragon/assets/119673958/e879f9d1-141a-413b-954a-070db9e5f4b7)

**Solution 2**
The Header can be adjusted to hide these buttons in the header section
![Screenshot 2024-01-19 074400](https://github.com/OWASP/www-project-threat-dragon/assets/119673958/27ac63c4-da10-49f5-a4c7-01a283fcbe0d)

I would like to contribute to solve this issue.

**Comment by jgadsden** [comment]
Hello @Santhoshmani1 , this is not something that is under the control of this repository. The style and layout of these panes are generated by the OWASP organisation, so an issue would have to be raised on the [github.io](https://github.com/OWASP/owasp.github.io) repo
