### ISSUE TITLE
Standardize Docker Image Location

### ISSUE THREAD

**Issue by lreading** [OWASP/www-project-threat-dragon#84]
**Describe what change you would like**:
The docker image is sometimes referenced as `threatdragon/owasp-threat-dragon`, but in the [README](https://github.com/owasp/threat-dragon?tab=readme-ov-file#docker-from-dockerhub) it states that the image is maintained in the OWASP org (awesome, btw! I know that this has been a wishlist item for a long time now!)

**Context**:
It would be great if we could reference the same org/image consistently. :)

**Comment by jgadsden** [comment]
Closed by pull request #85
